# Generated by Django 4.2.7 on 2023-12-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_itempictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempictures',
            name='name',
            field=models.CharField(default='itemname', max_length=50),
        ),
    ]
