# Generated by Django 4.2.7 on 2024-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cusorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusRatingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.IntegerField(default=1)),
                ('ratings', models.FloatField(default=0.0)),
                ('feedback', models.TextField(default='feedback', max_length=500)),
                ('username', models.CharField(default='username', max_length=200)),
            ],
        ),
    ]
