# Generated by Django 4.2.7 on 2023-12-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.fnasafety.com/wp-content/uploads/2016/04/ComingSoon2-fnasafety.png', max_length=500),
        ),
    ]
