# Generated by Django 4.2.7 on 2023-12-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae ratione ipsum tenetur quos expedita distinctio eligendi ea rem eum accusamus sit, dolore possimus tempore, veritatis qui dignissimos officiis fugiat quibusdam.', max_length=500),
        ),
    ]
