# Generated by Django 4.2.7 on 2023-12-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_for_useer_item_prod_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='for_useer',
            new_name='for_user',
        ),
    ]
