# Generated by Django 4.2.7 on 2024-01-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_remove_item_user_item_added_by_alter_item_rest_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('prod_code', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('operation_type', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
    ]
